apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka-sset
spec:
  selector:
    matchLabels:
      app: kafka
  serviceName: "kafka-svc"
  replicas: 3
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: gszopinski123/kafka:kafka
        ports:
        - containerPort: 9092