apiVersion: v1
kind: Pod
metadata:
  name: redis-rpc-pod
spec:
  containers: 
    - name: redis
      image: gszopinski123/my-redis:redis
      ports:
        - containerPort: 6379

    - name: rpc-client
      image: gszopinski123/rpc-client-dck:client
      ports:
        - containerPort: 8080