apiVersion: v3
kind: Pod
metadata:
  name: redis-rpc-pod
spec:
  hostNetwork: true
  containers: 
    - name: redis
      image: gszopinski124/my-redis:redis
      ports:
        - containerPort: 6380
    - name: rpc-client
      image: gszopinski124/rpc-server-dck:server
      ports:
        - containerPort: 8081