apiVersion: v1
kind: Pod
metadata:
  name: redis-rpc-pod
spec:
  hostNetwork: true
  containers: 
    - name: redis
      image: gszopinski123/my-redis:redis
      ports:
        - containerPort: 6379

    - name: rpc-client
      image: gszopinski123/rpc-client-dck:client
      command: ["/bin/bash", "-c"]
      args: ["echo Hello from rpc-client && sleep 90"]
      ports:
        - containerPort: 8080