FROM ubuntu:latest


RUN apt-get update && apt-get install -y g++
COPY src/rpc-server-dck .
COPY third_party .
RUN mkdir -p build/executables
RUN g++ -IreverseRPC/include \
	reverseRPC/include/rrpc.cpp \ 
	server.cpp \
	-o build/executables/server-dck

CMD ["./build/executables/server-dck"]